env:
  browser: true
  es6: true
  node: true
extends:
  - 'prettier'
  - 'prettier/@typescript-eslint'
settings:
  react:
    version: detect
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  'no-console': 'off'
  indent:
    - warn
    - tab
  linebreak-style: 'off'
  quotes:
    - error
    - single
  semi:
    - error
    - never
